import { Button, VerticalBox, LineEdit, HorizontalBox, TextEdit } from "std-widgets.slint";

export component LoginPage inherits Window {
    no-frame: false;
    resize-border-width: 10px;
    title: "Report page";
    width: 500px;
    height: 350px;
    always-on-top: true;
    full-screen: false;
    background: #12447d;

    in property <string> duration;

    callback send_report(text: string);

    VerticalBox {
        alignment: LayoutAlignment.stretch;
        spacing: 5px;
        visible: true;
        width: 100%;

        Rectangle {
            background: #12447d;
            width: 100%;
            height: 50px;

            Text {
                font-size: 15px;
                font-weight: 600;
                height: 50px;
                y: 13px;
                width: 450px;
                wrap: TextWrap.char-wrap;
                x: 19px;
                stroke-style: TextStrokeStyle.center;
                text: "Percebemos que você ficou " + duration + " minutos fora,\nquer nos contar o que aconteceu?";
                letter-spacing: 0.2px;
                overflow: TextOverflow.elide;
                color: #d8d8d8;
                vertical-alignment: TextVerticalAlignment.top;
                horizontal-alignment: center;
            }
        }

    }

    Rectangle {
        background: #e6e6e6;
        border-width: 25px;
        clip: true;
        border-color: #12447D;
        border-radius: 30px;
        width: 100%;
        height: 200px;

        VerticalBox {
            accessible-role: AccessibleRole.none;
            alignment: LayoutAlignment.space-between;
            spacing: 10px;
            visible: true;
            padding: 10px;

            Rectangle {
                height: 6px;
            }
        }
    }

    Button {
        accessible-role: AccessibleRole.checkbox;
        primary: true;
        text: "Enviar";
        x: 223px;
        y: 294px;

        clicked => {
            send_report(text-input.text);
        }
    }

    text-input := TextInput {
        single-line: false;
        text: "";
        padding-left: 10px;
        width: 400px;
        wrap: TextWrap.char-wrap;
        color: #000000;
        enabled: true;
        font-italic: false;
        font-size: 15px;
        font-weight: 600;
        height: 120px;
        horizontal-alignment: TextHorizontalAlignment.left;
        input-type: InputType.text;
    }
}
